### ISSUE TITLE
上传主题时出现的问题

### ISSUE THREAD

**Issue by twt898xu** [KINGMJ/maple#3]
大佬你好，
我上传你的主题时，ghost会报错
我用的是docker+官方镜像
请问该怎么解决比较好
![image](https://user-images.githubusercontent.com/28769187/34759526-e0ba7c10-f616-11e7-8f6e-31efd52c49ea.png)
![image](https://user-images.githubusercontent.com/28769187/34760514-1bb6e1ba-f61b-11e7-857d-810d1ca9f0bc.png)

**Comment by KINGMJ** [comment]
@mcxu233 我写这个主题时版本还是0，现在官方推出1.x的正式版了，语法都要调整。去年一直没有时间更新，我近期会推出支持1.x版本的和详细教程
